services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URI=mongodb+srv://neluwah:T4aNDkKFYnv8HqJa@cluster0.oltny.mongodb.net/employeeManagement?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo:6.0
    container_name: employee-management-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: